# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160303_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Post', unique=True),
        ),
    ]
